pipeline {
    parameters{booleanParam(name: 'isTest', defaultValue: false, description: "set this if you wanted to run test stage")}
    agent {label 'master'}

    stages{

          stage('testingDirectory')
        {
            steps{
                dir('src')
                {
                sh " pwd "

                }
            }
        }
        
         stage('cleanup')
        {
            steps{
                sh " mvn clean "
            }
        }
        stage('compile')
        {
            steps{
                sh " mvn compile "
            }
        }

        stage('package')
        {
            steps{
                sh " mvn package "
            }
        }

          stage('install')
        {
            steps{
                dir('$WORKSPACE')
                {
                sh " mvn install "

                }
            }
        }

          stage('test')
        {
            when { expression { return (params.isTest == true)} }
            steps{
                sh "mvn test"
            }
        }
		}
 }
